services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2026_travel_flask
    depends_on:
      mariadb:
        condition: service_healthy
    mem_limit: 256m
    cpus: 0.50
    ports:
      - 8000:8000 # 0 - 1024 reserved. Use any port from 1025 to 65535
    volumes:
      - .:/app
      - flask_sessions:/app/flask_session

  mariadb:
    image: mariadb:10.6.20
    container_name: 2026_travel_mariadb
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    mem_limit: 256m
    cpus: 0.50

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 2026_travel_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 8080:80
    mem_limit: 256m
    cpus: 0.50

volumes:
  mariadb_data:
  flask_sessions:
